name: glowtts
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.1
  - python=3.8
  - pytorch-gpu=1.8.0 
  - sox=14.4.2
  - pip:
    - cython==0.29.12 
    - librosa==0.7.1 
    - numba==0.48 
    - unidecode 
    - inflect 
    - tensorboard 
    - matplotlib 
    - wandb 
    - future
    - packaging
    - sox==1.4.1
    - tqdm==4.60.0
